---
title: "Content Usage Report"
output: blastula::blastula_email
---
```{r setup_email, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
default_content_title <- "Unknown (Deleted Content?)"
```

```{r custom_email}
content_summary <- data_arr$content %>% 
  group_by(content_guid) %>% 
  summarize(visits = n()) %>% 
  arrange(desc(visits)) %>% 
  head() %>% 
  mutate(name = purrr::map_chr(content_guid, ~ content_title(client, .x, default_content_title)))

app_summary <- data_arr$shiny %>% 
  group_by(content_guid) %>% 
  summarize(visits = n()) %>% 
  arrange(desc(visits)) %>% 
  head() %>% 
  mutate(name = purrr::map_chr(content_guid, ~ content_title(client, .x, default_content_title)))

leaderboard <- dplyr::bind_rows(app_summary, content_summary) %>%
  arrange(desc(visits)) %>%
  ggplot(., aes(reorder(name, visits), visits)) + 
     geom_bar(stat = "identity") +  
     coord_flip() + 
     theme_rstudio() + 
     labs(
       y = "Visits",
       x = NULL
     )
```

Hi Data Science Team!

Here is the top viewed content for the last `r days_back` days:

```{r add_plot_prep, message=FALSE, include=FALSE}
img_path <- tempfile(fileext = ".png")
png(img_path)
leaderboard
dev.off()
```

```{r add_plot, results='asis'}
htmltools::img(src = knitr::image_uri(img_path))
```

Best,

RStudio Connect
